service-values:
  em-srv:
    type: enterprise-messaging
    instance: debbd2ca-88f1-41a6-bf86-fa983e974863 
    key: emskey
  destination-srv:
    type: destination
    instance: 4229174e-3f7c-47df-9a56-d3c570a8b83e
    key: destkey
secret-values:
  destination-name:
    name:
      name: RegisteredoData
      attachmentSrvApi: API_CV_ATTACHMENT_SRV
      businessPartnerSrvApi: API_BUSINESS_PARTNER
      businessObjectTypeName: BUS1006
config-values:
  amqp-service-config:
    amqp:
      incoming:
        inp1:
          sourceAddress: queue:refapps/bpems/abc/serverlessQueue
          sndSettleMode: 0
          rcvSettleMode: 0
          maxLinkCredit: 50
    bind:
      rules:
        - filter:
            incoming: inp1
          action:
            function: qrcodegenerator
            failure: accept
            content: application/json
